#!/bin/bash

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

sudo apt-get update

sudo apt install fontconfig openjdk-17-jre

sudo apt-get install jenkins

sudo systemctl start jenkins
